### ISSUE TITLE
Blurred text on 4k (3840*2160) screen in the miniquad demo

### ISSUE THREAD

**Issue by Athanaze** [emilk/emigui#10]
Hello,

I noticed that in the miniquad web demo <https://not-fl3.github.io/miniquad-samples/emigui.html> the text is blurred.
I tested it on both Firefox and Brave (chromium based) and in both cases the text is rendered in the same way.
Here is a screenshot with Firefox on the left and Brave on the right : <https://imgur.com/LIdPU6d>
The text become clear when I zoom out (at 67% zoom on brave the text is clear). 

But the Egui feature demo <https://emilk.github.io/emigui/index.html> is rendering sharp text : <https://imgur.com/pPRb14W>

I noticed that imgur heavily rezises/compresses the screenshots I linked, so the blurriness of the text is not so clear but I can send them by email if you want (the text really is blurry).

I am on Linux 64bit (Manjaro) with a RTX 2080.

Thank you for your awesome work, I wish you the best of luck with this project :+1:

**Comment by emilk** [comment]
Blurry text is likely an issue with HDPI support. Looking at https://github.com/not-fl3/emigui-miniquad/blob/master/examples/test_window.rs I can see that `raw_input.screen_size` is set, but `raw_input.pixels_per_point` is not. This is most likely the culprit. I suggest opening a ticket or PR on https://github.com/not-fl3/emigui-miniquad

**Comment by JustinRyanH** [comment]
@emilk  I know this was closed a while ago, but I ended up implementing my own version in miniquad, and I was able to get a much crisper to version by rendering egui to it's own render target at double the resolution of the screen. I definitely would suggest to backend implementer to do render the UI to it's own render target anyways, but just  a heads up

**Comment by emilk** [comment]
@JustinRyanH Sounds like your miniquad integration is better (and more up-to-date) than the one at https://github.com/not-fl3/emigui-miniquad - would you mind publishing it to crates.io so others can also make use of it?

**Comment by JustinRyanH** [comment]
@emilk I'll do one better. I'll talk to not-fl3 and see if I can get a PR to fix his.
